[MANIFEST]
	version = "1.0"

[APPLICATION]
	name = "LavaMail"
	version = "1.0"
	description = "Lava Mail application"
	type = "angular"

	moduleName = "LavaMail"

	dependencies = [
		"LavaUtils",
		"lavaboom.api",
		"ui.router",
		"ui.bootstrap",
		"ui.select",
		"textAngular",
		"pascalprecht.translate",
		"infinite-scroll",
		"angular-co",
		"ngAutodisable",
		"cfp.hotkeys",
		"yaru22.angular-timeago",
		"dialogs.main",
		"ngMessages"
	]

	productionOnlyDependencies = [
	]

	vendorDependencies = [
		"bower@angular-bootstrap/ui-bootstrap.js",
		"bower@angular-bootstrap/ui-bootstrap-tpls.js",
		"bower@angular-ui-select/dist/select.js",
		"bower@textAngular/dist/textAngular-rangy.min.js",
		"bower@textAngular/dist/textAngular.min.js",
		"bower@ngInfiniteScroll/build/ng-infinite-scroll.js",
		"bower@angular-hotkeys/build/hotkeys.js",
		"bower@angular-timeago/src/timeAgo.js",
		"bower@angular-dialog-service/dist/dialogs.min.js"
	]